// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OperationRequestHistoryEntries struct {
	ID                 int64
	OperationRequestID int64
	Kind               string
	Step               *string
	Message            string
	DetailsJson        []byte
	CreatedAt          pgtype.Timestamptz
}

type OperationRequests struct {
	ID                              int64
	WebhookEventID                  *int64
	WebhookEventTriggerEvaluationID *int64
	RepositoryID                    int64
	RepositoryTriggerID             *int64
	PullRequestID                   int64
	RuntimeEnvironmentID            *int64
	TargetRuntimeEnvironmentID      *int64
	OperationType                   string
	Source                          string
	Status                          string
	TargetPrHeadCommitSha           string
	IntentSnapshotJson              []byte
	Outcome                         *string
	LastError                       *string
	HandledAt                       pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
	CurrentStep                     string
	CurrentStepState                string
	CurrentStepDetailsJson          []byte
}

type Ping struct {
	ID       int64
	PingedAt pgtype.Timestamptz
}

type PullRequests struct {
	ID                              int64
	RepositoryID                    int64
	PRNumber                        int64
	GithubPullRequestID             *int64
	CurrentHeadCommitSha            string
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	CurrentSourceGithubRepositoryID int64
	CurrentSourceOwner              string
	CurrentSourceName               string
	CurrentSourceFullName           string
}

type Repositories struct {
	ID                   int64
	GithubRepositoryID   int64
	GithubInstallationID int64
	Owner                string
	Name                 string
	FullName             string
	HtmlUrl              string
	IsPrivate            bool
	Enabled              bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type RepositoryEnvironmentVariables struct {
	ID           int64
	RepositoryID int64
	Name         string
	Value        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RepositoryEventFamilies struct {
	ID             int64
	RepositoryID   int64
	EventFamilyKey string
	Enabled        bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RepositoryRuntimeSettings struct {
	RepositoryID       int64
	ComposeFilePath    *string
	ExposedServiceName *string
	ExposedServicePort *int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type RepositoryTriggers struct {
	ID           int64
	RepositoryID int64
	Type         string
	Enabled      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RuntimeEnvironmentDeployments struct {
	RuntimeEnvironmentID           int64
	Backend                        string
	FrozenRuntimeSettingsJson      []byte
	FrozenEnvironmentVariablesJson []byte
	DeploymentMetadataJson         []byte
	CreatedAt                      pgtype.Timestamptz
	UpdatedAt                      pgtype.Timestamptz
}

type RuntimeEnvironments struct {
	ID                       int64
	RepositoryID             int64
	PullRequestID            int64
	Type                     string
	Status                   string
	TargetPrHeadCommitSha    string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	SourceGithubRepositoryID int64
	SourceOwner              string
	SourceName               string
	SourceFullName           string
	WorkspaceLocator         *string
}

type TriggerDispatches struct {
	ID                              int64
	WebhookEventID                  int64
	WebhookEventTriggerEvaluationID int64
	RepositoryID                    int64
	RepositoryTriggerID             int64
	DispatchType                    string
	Status                          string
	DispatchPayloadJson             []byte
	LastError                       *string
	ProcessedAt                     pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
}

type WebhookEventTriggerEvaluations struct {
	ID                  int64
	WebhookEventID      int64
	RepositoryTriggerID int64
	Matched             bool
	Reason              string
	TriggerSnapshotJson []byte
	CreatedAt           pgtype.Timestamptz
}

type WebhookEvents struct {
	ID                 int64
	DeliveryID         string
	GithubEvent        string
	EventType          string
	RepositoryID       *int64
	GithubRepositoryID *int64
	Status             string
	IgnoredReason      *string
	FailureMessage     *string
	PayloadJson        []byte
	CreatedAt          pgtype.Timestamptz
}
