// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation_requests.sql

package sqlc

import (
	"context"
)

const getOperationRequestByID = `-- name: GetOperationRequestByID :one
SELECT
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    pull_request_id,
    runtime_environment_id,
    target_runtime_environment_id,
    operation_type,
    source,
    status,
    target_pr_head_commit_sha,
    intent_snapshot_json,
    outcome,
    last_error,
    handled_at,
    created_at,
    current_step,
    current_step_state,
    current_step_details_json
FROM operation_requests
WHERE id = $1
`

func (q *Queries) GetOperationRequestByID(ctx context.Context, id int64) (OperationRequests, error) {
	row := q.db.QueryRow(ctx, getOperationRequestByID, id)
	var i OperationRequests
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.PullRequestID,
		&i.RuntimeEnvironmentID,
		&i.TargetRuntimeEnvironmentID,
		&i.OperationType,
		&i.Source,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.IntentSnapshotJson,
		&i.Outcome,
		&i.LastError,
		&i.HandledAt,
		&i.CreatedAt,
		&i.CurrentStep,
		&i.CurrentStepState,
		&i.CurrentStepDetailsJson,
	)
	return i, err
}

const insertOperationRequest = `-- name: InsertOperationRequest :one
INSERT INTO operation_requests (
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    pull_request_id,
    runtime_environment_id,
    target_runtime_environment_id,
    operation_type,
    source,
    status,
    target_pr_head_commit_sha,
    intent_snapshot_json,
    current_step,
    current_step_state,
    current_step_details_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    pull_request_id,
    runtime_environment_id,
    target_runtime_environment_id,
    operation_type,
    source,
    status,
    target_pr_head_commit_sha,
    intent_snapshot_json,
    outcome,
    last_error,
    handled_at,
    created_at,
    current_step,
    current_step_state,
    current_step_details_json
`

type InsertOperationRequestParams struct {
	WebhookEventID                  *int64
	WebhookEventTriggerEvaluationID *int64
	RepositoryID                    int64
	RepositoryTriggerID             *int64
	PullRequestID                   int64
	RuntimeEnvironmentID            *int64
	TargetRuntimeEnvironmentID      *int64
	OperationType                   string
	Source                          string
	Status                          string
	TargetPrHeadCommitSha           string
	IntentSnapshotJson              []byte
	CurrentStep                     string
	CurrentStepState                string
	CurrentStepDetailsJson          []byte
}

func (q *Queries) InsertOperationRequest(ctx context.Context, arg InsertOperationRequestParams) (OperationRequests, error) {
	row := q.db.QueryRow(ctx, insertOperationRequest,
		arg.WebhookEventID,
		arg.WebhookEventTriggerEvaluationID,
		arg.RepositoryID,
		arg.RepositoryTriggerID,
		arg.PullRequestID,
		arg.RuntimeEnvironmentID,
		arg.TargetRuntimeEnvironmentID,
		arg.OperationType,
		arg.Source,
		arg.Status,
		arg.TargetPrHeadCommitSha,
		arg.IntentSnapshotJson,
		arg.CurrentStep,
		arg.CurrentStepState,
		arg.CurrentStepDetailsJson,
	)
	var i OperationRequests
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.PullRequestID,
		&i.RuntimeEnvironmentID,
		&i.TargetRuntimeEnvironmentID,
		&i.OperationType,
		&i.Source,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.IntentSnapshotJson,
		&i.Outcome,
		&i.LastError,
		&i.HandledAt,
		&i.CreatedAt,
		&i.CurrentStep,
		&i.CurrentStepState,
		&i.CurrentStepDetailsJson,
	)
	return i, err
}

const listWebhookEventOperationRequests = `-- name: ListWebhookEventOperationRequests :many
SELECT
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    pull_request_id,
    runtime_environment_id,
    target_runtime_environment_id,
    operation_type,
    source,
    status,
    target_pr_head_commit_sha,
    intent_snapshot_json,
    outcome,
    last_error,
    handled_at,
    created_at,
    current_step,
    current_step_state,
    current_step_details_json
FROM operation_requests
WHERE operation_requests.webhook_event_id = $1
ORDER BY operation_requests.id ASC
`

func (q *Queries) ListWebhookEventOperationRequests(ctx context.Context, webhookEventID *int64) ([]OperationRequests, error) {
	rows, err := q.db.Query(ctx, listWebhookEventOperationRequests, webhookEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationRequests
	for rows.Next() {
		var i OperationRequests
		if err := rows.Scan(
			&i.ID,
			&i.WebhookEventID,
			&i.WebhookEventTriggerEvaluationID,
			&i.RepositoryID,
			&i.RepositoryTriggerID,
			&i.PullRequestID,
			&i.RuntimeEnvironmentID,
			&i.TargetRuntimeEnvironmentID,
			&i.OperationType,
			&i.Source,
			&i.Status,
			&i.TargetPrHeadCommitSha,
			&i.IntentSnapshotJson,
			&i.Outcome,
			&i.LastError,
			&i.HandledAt,
			&i.CreatedAt,
			&i.CurrentStep,
			&i.CurrentStepState,
			&i.CurrentStepDetailsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOperationRequestFailed = `-- name: MarkOperationRequestFailed :one
UPDATE operation_requests
SET
    runtime_environment_id = COALESCE($2, runtime_environment_id),
    status = 'failed',
    outcome = $3,
    last_error = $4,
    handled_at = NOW()
WHERE id = $1
RETURNING
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    pull_request_id,
    runtime_environment_id,
    target_runtime_environment_id,
    operation_type,
    source,
    status,
    target_pr_head_commit_sha,
    intent_snapshot_json,
    outcome,
    last_error,
    handled_at,
    created_at,
    current_step,
    current_step_state,
    current_step_details_json
`

type MarkOperationRequestFailedParams struct {
	ID                   int64
	RuntimeEnvironmentID *int64
	Outcome              *string
	LastError            *string
}

func (q *Queries) MarkOperationRequestFailed(ctx context.Context, arg MarkOperationRequestFailedParams) (OperationRequests, error) {
	row := q.db.QueryRow(ctx, markOperationRequestFailed,
		arg.ID,
		arg.RuntimeEnvironmentID,
		arg.Outcome,
		arg.LastError,
	)
	var i OperationRequests
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.PullRequestID,
		&i.RuntimeEnvironmentID,
		&i.TargetRuntimeEnvironmentID,
		&i.OperationType,
		&i.Source,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.IntentSnapshotJson,
		&i.Outcome,
		&i.LastError,
		&i.HandledAt,
		&i.CreatedAt,
		&i.CurrentStep,
		&i.CurrentStepState,
		&i.CurrentStepDetailsJson,
	)
	return i, err
}

const markOperationRequestHandled = `-- name: MarkOperationRequestHandled :one
UPDATE operation_requests
SET
    runtime_environment_id = COALESCE($2, runtime_environment_id),
    status = 'handled',
    outcome = $3,
    last_error = NULL,
    handled_at = NOW()
WHERE id = $1
RETURNING
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    pull_request_id,
    runtime_environment_id,
    target_runtime_environment_id,
    operation_type,
    source,
    status,
    target_pr_head_commit_sha,
    intent_snapshot_json,
    outcome,
    last_error,
    handled_at,
    created_at,
    current_step,
    current_step_state,
    current_step_details_json
`

type MarkOperationRequestHandledParams struct {
	ID                   int64
	RuntimeEnvironmentID *int64
	Outcome              *string
}

func (q *Queries) MarkOperationRequestHandled(ctx context.Context, arg MarkOperationRequestHandledParams) (OperationRequests, error) {
	row := q.db.QueryRow(ctx, markOperationRequestHandled, arg.ID, arg.RuntimeEnvironmentID, arg.Outcome)
	var i OperationRequests
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.PullRequestID,
		&i.RuntimeEnvironmentID,
		&i.TargetRuntimeEnvironmentID,
		&i.OperationType,
		&i.Source,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.IntentSnapshotJson,
		&i.Outcome,
		&i.LastError,
		&i.HandledAt,
		&i.CreatedAt,
		&i.CurrentStep,
		&i.CurrentStepState,
		&i.CurrentStepDetailsJson,
	)
	return i, err
}

const setOperationRequestProgress = `-- name: SetOperationRequestProgress :one
UPDATE operation_requests
SET
    runtime_environment_id = COALESCE($2, runtime_environment_id),
    current_step = $3,
    current_step_state = $4,
    current_step_details_json = $5
WHERE id = $1
RETURNING
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    pull_request_id,
    runtime_environment_id,
    target_runtime_environment_id,
    operation_type,
    source,
    status,
    target_pr_head_commit_sha,
    intent_snapshot_json,
    outcome,
    last_error,
    handled_at,
    created_at,
    current_step,
    current_step_state,
    current_step_details_json
`

type SetOperationRequestProgressParams struct {
	ID                     int64
	RuntimeEnvironmentID   *int64
	CurrentStep            string
	CurrentStepState       string
	CurrentStepDetailsJson []byte
}

func (q *Queries) SetOperationRequestProgress(ctx context.Context, arg SetOperationRequestProgressParams) (OperationRequests, error) {
	row := q.db.QueryRow(ctx, setOperationRequestProgress,
		arg.ID,
		arg.RuntimeEnvironmentID,
		arg.CurrentStep,
		arg.CurrentStepState,
		arg.CurrentStepDetailsJson,
	)
	var i OperationRequests
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.PullRequestID,
		&i.RuntimeEnvironmentID,
		&i.TargetRuntimeEnvironmentID,
		&i.OperationType,
		&i.Source,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.IntentSnapshotJson,
		&i.Outcome,
		&i.LastError,
		&i.HandledAt,
		&i.CreatedAt,
		&i.CurrentStep,
		&i.CurrentStepState,
		&i.CurrentStepDetailsJson,
	)
	return i, err
}
