// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation_request_history.sql

package sqlc

import (
	"context"
)

const insertOperationRequestHistoryEntry = `-- name: InsertOperationRequestHistoryEntry :one
INSERT INTO operation_request_history_entries (
    operation_request_id,
    kind,
    step,
    message,
    details_json
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    operation_request_id,
    kind,
    step,
    message,
    details_json,
    created_at
`

type InsertOperationRequestHistoryEntryParams struct {
	OperationRequestID int64
	Kind               string
	Step               *string
	Message            string
	DetailsJson        []byte
}

func (q *Queries) InsertOperationRequestHistoryEntry(ctx context.Context, arg InsertOperationRequestHistoryEntryParams) (OperationRequestHistoryEntries, error) {
	row := q.db.QueryRow(ctx, insertOperationRequestHistoryEntry,
		arg.OperationRequestID,
		arg.Kind,
		arg.Step,
		arg.Message,
		arg.DetailsJson,
	)
	var i OperationRequestHistoryEntries
	err := row.Scan(
		&i.ID,
		&i.OperationRequestID,
		&i.Kind,
		&i.Step,
		&i.Message,
		&i.DetailsJson,
		&i.CreatedAt,
	)
	return i, err
}

const listOperationRequestHistoryEntriesByOperationRequestID = `-- name: ListOperationRequestHistoryEntriesByOperationRequestID :many
SELECT
    id,
    operation_request_id,
    kind,
    step,
    message,
    details_json,
    created_at
FROM operation_request_history_entries
WHERE operation_request_id = $1
ORDER BY id ASC
`

func (q *Queries) ListOperationRequestHistoryEntriesByOperationRequestID(ctx context.Context, operationRequestID int64) ([]OperationRequestHistoryEntries, error) {
	rows, err := q.db.Query(ctx, listOperationRequestHistoryEntriesByOperationRequestID, operationRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationRequestHistoryEntries
	for rows.Next() {
		var i OperationRequestHistoryEntries
		if err := rows.Scan(
			&i.ID,
			&i.OperationRequestID,
			&i.Kind,
			&i.Step,
			&i.Message,
			&i.DetailsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
