// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ping.sql

package sqlc

import (
	"context"
)

const getPing = `-- name: GetPing :one
SELECT id, pinged_at FROM _ping ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetPing(ctx context.Context) (Ping, error) {
	row := q.db.QueryRow(ctx, getPing)
	var i Ping
	err := row.Scan(&i.ID, &i.PingedAt)
	return i, err
}

const insertPing = `-- name: InsertPing :one
INSERT INTO _ping DEFAULT VALUES
RETURNING id, pinged_at
`

func (q *Queries) InsertPing(ctx context.Context) (Ping, error) {
	row := q.db.QueryRow(ctx, insertPing)
	var i Ping
	err := row.Scan(&i.ID, &i.PingedAt)
	return i, err
}

const listPings = `-- name: ListPings :many
SELECT id, pinged_at
FROM _ping
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListPings(ctx context.Context, limit int32) ([]Ping, error) {
	rows, err := q.db.Query(ctx, listPings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ping
	for rows.Next() {
		var i Ping
		if err := rows.Scan(&i.ID, &i.PingedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
