// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_requests.sql

package sqlc

import (
	"context"
)

const getPullRequestByRepositoryIDAndPRNumber = `-- name: GetPullRequestByRepositoryIDAndPRNumber :one
SELECT
    id,
    repository_id,
    pr_number,
    github_pull_request_id,
    current_head_commit_sha,
    created_at,
    updated_at,
    current_source_github_repository_id,
    current_source_owner,
    current_source_name,
    current_source_full_name
FROM pull_requests
WHERE repository_id = $1
  AND pr_number = $2
`

type GetPullRequestByRepositoryIDAndPRNumberParams struct {
	RepositoryID int64
	PRNumber     int64
}

func (q *Queries) GetPullRequestByRepositoryIDAndPRNumber(ctx context.Context, arg GetPullRequestByRepositoryIDAndPRNumberParams) (PullRequests, error) {
	row := q.db.QueryRow(ctx, getPullRequestByRepositoryIDAndPRNumber, arg.RepositoryID, arg.PRNumber)
	var i PullRequests
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PRNumber,
		&i.GithubPullRequestID,
		&i.CurrentHeadCommitSha,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentSourceGithubRepositoryID,
		&i.CurrentSourceOwner,
		&i.CurrentSourceName,
		&i.CurrentSourceFullName,
	)
	return i, err
}

const upsertPullRequestAnchor = `-- name: UpsertPullRequestAnchor :one
INSERT INTO pull_requests (
    repository_id,
    pr_number,
    github_pull_request_id,
    current_head_commit_sha,
    current_source_github_repository_id,
    current_source_owner,
    current_source_name,
    current_source_full_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (repository_id, pr_number) DO UPDATE
SET
    github_pull_request_id = COALESCE(EXCLUDED.github_pull_request_id, pull_requests.github_pull_request_id),
    current_head_commit_sha = EXCLUDED.current_head_commit_sha,
    current_source_github_repository_id = EXCLUDED.current_source_github_repository_id,
    current_source_owner = EXCLUDED.current_source_owner,
    current_source_name = EXCLUDED.current_source_name,
    current_source_full_name = EXCLUDED.current_source_full_name,
    updated_at = NOW()
RETURNING
    id,
    repository_id,
    pr_number,
    github_pull_request_id,
    current_head_commit_sha,
    created_at,
    updated_at,
    current_source_github_repository_id,
    current_source_owner,
    current_source_name,
    current_source_full_name
`

type UpsertPullRequestAnchorParams struct {
	RepositoryID                    int64
	PRNumber                        int64
	GithubPullRequestID             *int64
	CurrentHeadCommitSha            string
	CurrentSourceGithubRepositoryID int64
	CurrentSourceOwner              string
	CurrentSourceName               string
	CurrentSourceFullName           string
}

func (q *Queries) UpsertPullRequestAnchor(ctx context.Context, arg UpsertPullRequestAnchorParams) (PullRequests, error) {
	row := q.db.QueryRow(ctx, upsertPullRequestAnchor,
		arg.RepositoryID,
		arg.PRNumber,
		arg.GithubPullRequestID,
		arg.CurrentHeadCommitSha,
		arg.CurrentSourceGithubRepositoryID,
		arg.CurrentSourceOwner,
		arg.CurrentSourceName,
		arg.CurrentSourceFullName,
	)
	var i PullRequests
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PRNumber,
		&i.GithubPullRequestID,
		&i.CurrentHeadCommitSha,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentSourceGithubRepositoryID,
		&i.CurrentSourceOwner,
		&i.CurrentSourceName,
		&i.CurrentSourceFullName,
	)
	return i, err
}
