// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepositoryByGitHubRepositoryID = `-- name: GetRepositoryByGitHubRepositoryID :one
SELECT
    id,
    github_repository_id,
    github_installation_id,
    owner,
    name,
    full_name,
    html_url,
    is_private,
    enabled,
    created_at,
    updated_at
FROM repositories
WHERE github_repository_id = $1
`

func (q *Queries) GetRepositoryByGitHubRepositoryID(ctx context.Context, githubRepositoryID int64) (Repositories, error) {
	row := q.db.QueryRow(ctx, getRepositoryByGitHubRepositoryID, githubRepositoryID)
	var i Repositories
	err := row.Scan(
		&i.ID,
		&i.GithubRepositoryID,
		&i.GithubInstallationID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.HtmlUrl,
		&i.IsPrivate,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT
    id,
    github_repository_id,
    github_installation_id,
    owner,
    name,
    full_name,
    html_url,
    is_private,
    enabled,
    created_at,
    updated_at
FROM repositories
WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id int64) (Repositories, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repositories
	err := row.Scan(
		&i.ID,
		&i.GithubRepositoryID,
		&i.GithubInstallationID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.HtmlUrl,
		&i.IsPrivate,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT
    id,
    github_repository_id,
    github_installation_id,
    owner,
    name,
    full_name,
    html_url,
    is_private,
    enabled,
    created_at,
    updated_at
FROM repositories
ORDER BY id ASC
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repositories, error) {
	rows, err := q.db.Query(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repositories
	for rows.Next() {
		var i Repositories
		if err := rows.Scan(
			&i.ID,
			&i.GithubRepositoryID,
			&i.GithubInstallationID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.HtmlUrl,
			&i.IsPrivate,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryEnabled = `-- name: SetRepositoryEnabled :one
UPDATE repositories
SET
    enabled = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    github_repository_id,
    github_installation_id,
    owner,
    name,
    full_name,
    html_url,
    is_private,
    enabled,
    created_at,
    updated_at
`

type SetRepositoryEnabledParams struct {
	ID      int64
	Enabled bool
}

func (q *Queries) SetRepositoryEnabled(ctx context.Context, arg SetRepositoryEnabledParams) (Repositories, error) {
	row := q.db.QueryRow(ctx, setRepositoryEnabled, arg.ID, arg.Enabled)
	var i Repositories
	err := row.Scan(
		&i.ID,
		&i.GithubRepositoryID,
		&i.GithubInstallationID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.HtmlUrl,
		&i.IsPrivate,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :one
WITH upserted_repository AS (
    INSERT INTO repositories (
        github_repository_id,
        github_installation_id,
        owner,
        name,
        full_name,
        html_url,
        is_private
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7
    )
    ON CONFLICT (github_repository_id) DO UPDATE
    SET
        github_installation_id = EXCLUDED.github_installation_id,
        owner = EXCLUDED.owner,
        name = EXCLUDED.name,
        full_name = EXCLUDED.full_name,
        html_url = EXCLUDED.html_url,
        is_private = EXCLUDED.is_private,
        updated_at = NOW()
    RETURNING
        id,
        github_repository_id,
        github_installation_id,
        owner,
        name,
        full_name,
        html_url,
        is_private,
        enabled,
        created_at,
        updated_at
), ensured_runtime_settings AS (
    INSERT INTO repository_runtime_settings (repository_id)
    SELECT upserted_repository.id
    FROM upserted_repository
    ON CONFLICT (repository_id) DO NOTHING
)
SELECT
    id,
    github_repository_id,
    github_installation_id,
    owner,
    name,
    full_name,
    html_url,
    is_private,
    enabled,
    created_at,
    updated_at
FROM upserted_repository
`

type UpsertRepositoryParams struct {
	GithubRepositoryID   int64
	GithubInstallationID int64
	Owner                string
	Name                 string
	FullName             string
	HtmlUrl              string
	IsPrivate            bool
}

type UpsertRepositoryRow struct {
	ID                   int64
	GithubRepositoryID   int64
	GithubInstallationID int64
	Owner                string
	Name                 string
	FullName             string
	HtmlUrl              string
	IsPrivate            bool
	Enabled              bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (UpsertRepositoryRow, error) {
	row := q.db.QueryRow(ctx, upsertRepository,
		arg.GithubRepositoryID,
		arg.GithubInstallationID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.HtmlUrl,
		arg.IsPrivate,
	)
	var i UpsertRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.GithubRepositoryID,
		&i.GithubInstallationID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.HtmlUrl,
		&i.IsPrivate,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
