// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository_environment_variables.sql

package sqlc

import (
	"context"
)

const deleteRepositoryEnvironmentVariablesByRepositoryID = `-- name: DeleteRepositoryEnvironmentVariablesByRepositoryID :exec
DELETE FROM repository_environment_variables
WHERE repository_id = $1
`

func (q *Queries) DeleteRepositoryEnvironmentVariablesByRepositoryID(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, deleteRepositoryEnvironmentVariablesByRepositoryID, repositoryID)
	return err
}

const insertRepositoryEnvironmentVariable = `-- name: InsertRepositoryEnvironmentVariable :one
INSERT INTO repository_environment_variables (
    repository_id,
    name,
    value
) VALUES (
    $1, $2, $3
)
RETURNING
    id,
    repository_id,
    name,
    value,
    created_at,
    updated_at
`

type InsertRepositoryEnvironmentVariableParams struct {
	RepositoryID int64
	Name         string
	Value        string
}

func (q *Queries) InsertRepositoryEnvironmentVariable(ctx context.Context, arg InsertRepositoryEnvironmentVariableParams) (RepositoryEnvironmentVariables, error) {
	row := q.db.QueryRow(ctx, insertRepositoryEnvironmentVariable, arg.RepositoryID, arg.Name, arg.Value)
	var i RepositoryEnvironmentVariables
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoryEnvironmentVariablesByRepositoryID = `-- name: ListRepositoryEnvironmentVariablesByRepositoryID :many
SELECT
    id,
    repository_id,
    name,
    value,
    created_at,
    updated_at
FROM repository_environment_variables
WHERE repository_id = $1
ORDER BY name ASC, id ASC
`

func (q *Queries) ListRepositoryEnvironmentVariablesByRepositoryID(ctx context.Context, repositoryID int64) ([]RepositoryEnvironmentVariables, error) {
	rows, err := q.db.Query(ctx, listRepositoryEnvironmentVariablesByRepositoryID, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryEnvironmentVariables
	for rows.Next() {
		var i RepositoryEnvironmentVariables
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
