// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository_triggers.sql

package sqlc

import (
	"context"
)

const getRepositoryTriggerByID = `-- name: GetRepositoryTriggerByID :one
SELECT
    id,
    repository_id,
    type,
    enabled,
    created_at,
    updated_at
FROM repository_triggers
WHERE repository_id = $1
  AND id = $2
`

type GetRepositoryTriggerByIDParams struct {
	RepositoryID int64
	ID           int64
}

func (q *Queries) GetRepositoryTriggerByID(ctx context.Context, arg GetRepositoryTriggerByIDParams) (RepositoryTriggers, error) {
	row := q.db.QueryRow(ctx, getRepositoryTriggerByID, arg.RepositoryID, arg.ID)
	var i RepositoryTriggers
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Type,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRepositoryTriggers = `-- name: ListEnabledRepositoryTriggers :many
SELECT
    id,
    repository_id,
    type,
    enabled,
    created_at,
    updated_at
FROM repository_triggers
WHERE repository_id = $1
  AND enabled = TRUE
ORDER BY id ASC
`

func (q *Queries) ListEnabledRepositoryTriggers(ctx context.Context, repositoryID int64) ([]RepositoryTriggers, error) {
	rows, err := q.db.Query(ctx, listEnabledRepositoryTriggers, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryTriggers
	for rows.Next() {
		var i RepositoryTriggers
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Type,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryTriggers = `-- name: ListRepositoryTriggers :many
SELECT
    id,
    repository_id,
    type,
    enabled,
    created_at,
    updated_at
FROM repository_triggers
WHERE repository_id = $1
ORDER BY id ASC
`

func (q *Queries) ListRepositoryTriggers(ctx context.Context, repositoryID int64) ([]RepositoryTriggers, error) {
	rows, err := q.db.Query(ctx, listRepositoryTriggers, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryTriggers
	for rows.Next() {
		var i RepositoryTriggers
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Type,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryTriggerEnabled = `-- name: SetRepositoryTriggerEnabled :one
UPDATE repository_triggers
SET
    enabled = $3,
    updated_at = NOW()
WHERE repository_id = $1
  AND id = $2
RETURNING
    id,
    repository_id,
    type,
    enabled,
    created_at,
    updated_at
`

type SetRepositoryTriggerEnabledParams struct {
	RepositoryID int64
	ID           int64
	Enabled      bool
}

func (q *Queries) SetRepositoryTriggerEnabled(ctx context.Context, arg SetRepositoryTriggerEnabledParams) (RepositoryTriggers, error) {
	row := q.db.QueryRow(ctx, setRepositoryTriggerEnabled, arg.RepositoryID, arg.ID, arg.Enabled)
	var i RepositoryTriggers
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Type,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryTrigger = `-- name: UpsertRepositoryTrigger :one
INSERT INTO repository_triggers (
    repository_id,
    type,
    enabled
) VALUES (
    $1, $2, $3
)
ON CONFLICT (repository_id, type) DO UPDATE
SET
    enabled = EXCLUDED.enabled,
    updated_at = NOW()
RETURNING
    id,
    repository_id,
    type,
    enabled,
    created_at,
    updated_at
`

type UpsertRepositoryTriggerParams struct {
	RepositoryID int64
	Type         string
	Enabled      bool
}

func (q *Queries) UpsertRepositoryTrigger(ctx context.Context, arg UpsertRepositoryTriggerParams) (RepositoryTriggers, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryTrigger, arg.RepositoryID, arg.Type, arg.Enabled)
	var i RepositoryTriggers
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Type,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
