// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository_event_families.sql

package sqlc

import (
	"context"
)

const ensureRepositoryEventFamilies = `-- name: EnsureRepositoryEventFamilies :exec
INSERT INTO repository_event_families (
    repository_id,
    event_family_key,
    enabled
)
SELECT
    $1,
    unnest($2::text[]),
    TRUE
ON CONFLICT (repository_id, event_family_key) DO NOTHING
`

type EnsureRepositoryEventFamiliesParams struct {
	RepositoryID    int64
	EventFamilyKeys []string
}

func (q *Queries) EnsureRepositoryEventFamilies(ctx context.Context, arg EnsureRepositoryEventFamiliesParams) error {
	_, err := q.db.Exec(ctx, ensureRepositoryEventFamilies, arg.RepositoryID, arg.EventFamilyKeys)
	return err
}

const getRepositoryEventFamily = `-- name: GetRepositoryEventFamily :one
SELECT
    id,
    repository_id,
    event_family_key,
    enabled,
    created_at,
    updated_at
FROM repository_event_families
WHERE repository_id = $1
  AND event_family_key = $2
`

type GetRepositoryEventFamilyParams struct {
	RepositoryID   int64
	EventFamilyKey string
}

func (q *Queries) GetRepositoryEventFamily(ctx context.Context, arg GetRepositoryEventFamilyParams) (RepositoryEventFamilies, error) {
	row := q.db.QueryRow(ctx, getRepositoryEventFamily, arg.RepositoryID, arg.EventFamilyKey)
	var i RepositoryEventFamilies
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.EventFamilyKey,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoryEventFamilies = `-- name: ListRepositoryEventFamilies :many
SELECT
    id,
    repository_id,
    event_family_key,
    enabled,
    created_at,
    updated_at
FROM repository_event_families
WHERE repository_id = $1
ORDER BY id ASC
`

func (q *Queries) ListRepositoryEventFamilies(ctx context.Context, repositoryID int64) ([]RepositoryEventFamilies, error) {
	rows, err := q.db.Query(ctx, listRepositoryEventFamilies, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryEventFamilies
	for rows.Next() {
		var i RepositoryEventFamilies
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.EventFamilyKey,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryEventFamilyEnabled = `-- name: SetRepositoryEventFamilyEnabled :one
UPDATE repository_event_families
SET
    enabled = $3,
    updated_at = NOW()
WHERE repository_id = $1
  AND event_family_key = $2
RETURNING
    id,
    repository_id,
    event_family_key,
    enabled,
    created_at,
    updated_at
`

type SetRepositoryEventFamilyEnabledParams struct {
	RepositoryID   int64
	EventFamilyKey string
	Enabled        bool
}

func (q *Queries) SetRepositoryEventFamilyEnabled(ctx context.Context, arg SetRepositoryEventFamilyEnabledParams) (RepositoryEventFamilies, error) {
	row := q.db.QueryRow(ctx, setRepositoryEventFamilyEnabled, arg.RepositoryID, arg.EventFamilyKey, arg.Enabled)
	var i RepositoryEventFamilies
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.EventFamilyKey,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryEventFamily = `-- name: UpsertRepositoryEventFamily :one
INSERT INTO repository_event_families (
    repository_id,
    event_family_key,
    enabled
) VALUES (
    $1, $2, $3
)
ON CONFLICT (repository_id, event_family_key) DO UPDATE
SET
    enabled = EXCLUDED.enabled,
    updated_at = NOW()
RETURNING
    id,
    repository_id,
    event_family_key,
    enabled,
    created_at,
    updated_at
`

type UpsertRepositoryEventFamilyParams struct {
	RepositoryID   int64
	EventFamilyKey string
	Enabled        bool
}

func (q *Queries) UpsertRepositoryEventFamily(ctx context.Context, arg UpsertRepositoryEventFamilyParams) (RepositoryEventFamilies, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryEventFamily, arg.RepositoryID, arg.EventFamilyKey, arg.Enabled)
	var i RepositoryEventFamilies
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.EventFamilyKey,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
