// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository_runtime_settings.sql

package sqlc

import (
	"context"
)

const getRepositoryRuntimeSettingsByRepositoryID = `-- name: GetRepositoryRuntimeSettingsByRepositoryID :one
SELECT
    repository_id,
    compose_file_path,
    exposed_service_name,
    exposed_service_port,
    created_at,
    updated_at
FROM repository_runtime_settings
WHERE repository_id = $1
`

func (q *Queries) GetRepositoryRuntimeSettingsByRepositoryID(ctx context.Context, repositoryID int64) (RepositoryRuntimeSettings, error) {
	row := q.db.QueryRow(ctx, getRepositoryRuntimeSettingsByRepositoryID, repositoryID)
	var i RepositoryRuntimeSettings
	err := row.Scan(
		&i.RepositoryID,
		&i.ComposeFilePath,
		&i.ExposedServiceName,
		&i.ExposedServicePort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryRuntimeSettings = `-- name: UpsertRepositoryRuntimeSettings :one
INSERT INTO repository_runtime_settings (
    repository_id,
    compose_file_path,
    exposed_service_name,
    exposed_service_port
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (repository_id) DO UPDATE
SET
    compose_file_path = EXCLUDED.compose_file_path,
    exposed_service_name = EXCLUDED.exposed_service_name,
    exposed_service_port = EXCLUDED.exposed_service_port,
    updated_at = NOW()
RETURNING
    repository_id,
    compose_file_path,
    exposed_service_name,
    exposed_service_port,
    created_at,
    updated_at
`

type UpsertRepositoryRuntimeSettingsParams struct {
	RepositoryID       int64
	ComposeFilePath    *string
	ExposedServiceName *string
	ExposedServicePort *int32
}

func (q *Queries) UpsertRepositoryRuntimeSettings(ctx context.Context, arg UpsertRepositoryRuntimeSettingsParams) (RepositoryRuntimeSettings, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryRuntimeSettings,
		arg.RepositoryID,
		arg.ComposeFilePath,
		arg.ExposedServiceName,
		arg.ExposedServicePort,
	)
	var i RepositoryRuntimeSettings
	err := row.Scan(
		&i.RepositoryID,
		&i.ComposeFilePath,
		&i.ExposedServiceName,
		&i.ExposedServicePort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
