// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_environment_deployments.sql

package sqlc

import (
	"context"
)

const getRuntimeEnvironmentDeploymentByRuntimeEnvironmentID = `-- name: GetRuntimeEnvironmentDeploymentByRuntimeEnvironmentID :one
SELECT
    runtime_environment_id,
    backend,
    frozen_runtime_settings_json,
    frozen_environment_variables_json,
    deployment_metadata_json,
    created_at,
    updated_at
FROM runtime_environment_deployments
WHERE runtime_environment_id = $1
`

func (q *Queries) GetRuntimeEnvironmentDeploymentByRuntimeEnvironmentID(ctx context.Context, runtimeEnvironmentID int64) (RuntimeEnvironmentDeployments, error) {
	row := q.db.QueryRow(ctx, getRuntimeEnvironmentDeploymentByRuntimeEnvironmentID, runtimeEnvironmentID)
	var i RuntimeEnvironmentDeployments
	err := row.Scan(
		&i.RuntimeEnvironmentID,
		&i.Backend,
		&i.FrozenRuntimeSettingsJson,
		&i.FrozenEnvironmentVariablesJson,
		&i.DeploymentMetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRuntimeEnvironmentDeployment = `-- name: UpsertRuntimeEnvironmentDeployment :one
INSERT INTO runtime_environment_deployments (
    runtime_environment_id,
    backend,
    frozen_runtime_settings_json,
    frozen_environment_variables_json,
    deployment_metadata_json
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (runtime_environment_id) DO UPDATE
SET
    backend = EXCLUDED.backend,
    frozen_runtime_settings_json = EXCLUDED.frozen_runtime_settings_json,
    frozen_environment_variables_json = EXCLUDED.frozen_environment_variables_json,
    deployment_metadata_json = EXCLUDED.deployment_metadata_json,
    updated_at = NOW()
RETURNING
    runtime_environment_id,
    backend,
    frozen_runtime_settings_json,
    frozen_environment_variables_json,
    deployment_metadata_json,
    created_at,
    updated_at
`

type UpsertRuntimeEnvironmentDeploymentParams struct {
	RuntimeEnvironmentID           int64
	Backend                        string
	FrozenRuntimeSettingsJson      []byte
	FrozenEnvironmentVariablesJson []byte
	DeploymentMetadataJson         []byte
}

func (q *Queries) UpsertRuntimeEnvironmentDeployment(ctx context.Context, arg UpsertRuntimeEnvironmentDeploymentParams) (RuntimeEnvironmentDeployments, error) {
	row := q.db.QueryRow(ctx, upsertRuntimeEnvironmentDeployment,
		arg.RuntimeEnvironmentID,
		arg.Backend,
		arg.FrozenRuntimeSettingsJson,
		arg.FrozenEnvironmentVariablesJson,
		arg.DeploymentMetadataJson,
	)
	var i RuntimeEnvironmentDeployments
	err := row.Scan(
		&i.RuntimeEnvironmentID,
		&i.Backend,
		&i.FrozenRuntimeSettingsJson,
		&i.FrozenEnvironmentVariablesJson,
		&i.DeploymentMetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
