// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_environments.sql

package sqlc

import (
	"context"
)

const getLatestRuntimeEnvironmentByTarget = `-- name: GetLatestRuntimeEnvironmentByTarget :one
SELECT
    id,
    repository_id,
    pull_request_id,
    type,
    status,
    target_pr_head_commit_sha,
    created_at,
    updated_at,
    source_github_repository_id,
    source_owner,
    source_name,
    source_full_name,
    workspace_locator
FROM runtime_environments
WHERE repository_id = $1
  AND pull_request_id = $2
  AND type = $3
  AND target_pr_head_commit_sha = $4
ORDER BY id DESC
LIMIT 1
`

type GetLatestRuntimeEnvironmentByTargetParams struct {
	RepositoryID          int64
	PullRequestID         int64
	Type                  string
	TargetPrHeadCommitSha string
}

func (q *Queries) GetLatestRuntimeEnvironmentByTarget(ctx context.Context, arg GetLatestRuntimeEnvironmentByTargetParams) (RuntimeEnvironments, error) {
	row := q.db.QueryRow(ctx, getLatestRuntimeEnvironmentByTarget,
		arg.RepositoryID,
		arg.PullRequestID,
		arg.Type,
		arg.TargetPrHeadCommitSha,
	)
	var i RuntimeEnvironments
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PullRequestID,
		&i.Type,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceGithubRepositoryID,
		&i.SourceOwner,
		&i.SourceName,
		&i.SourceFullName,
		&i.WorkspaceLocator,
	)
	return i, err
}

const getRuntimeEnvironmentByID = `-- name: GetRuntimeEnvironmentByID :one
SELECT
    id,
    repository_id,
    pull_request_id,
    type,
    status,
    target_pr_head_commit_sha,
    created_at,
    updated_at,
    source_github_repository_id,
    source_owner,
    source_name,
    source_full_name,
    workspace_locator
FROM runtime_environments
WHERE id = $1
`

func (q *Queries) GetRuntimeEnvironmentByID(ctx context.Context, id int64) (RuntimeEnvironments, error) {
	row := q.db.QueryRow(ctx, getRuntimeEnvironmentByID, id)
	var i RuntimeEnvironments
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PullRequestID,
		&i.Type,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceGithubRepositoryID,
		&i.SourceOwner,
		&i.SourceName,
		&i.SourceFullName,
		&i.WorkspaceLocator,
	)
	return i, err
}

const insertRuntimeEnvironment = `-- name: InsertRuntimeEnvironment :one
INSERT INTO runtime_environments (
    repository_id,
    pull_request_id,
    type,
    status,
    target_pr_head_commit_sha,
    source_github_repository_id,
    source_owner,
    source_name,
    source_full_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING
    id,
    repository_id,
    pull_request_id,
    type,
    status,
    target_pr_head_commit_sha,
    created_at,
    updated_at,
    source_github_repository_id,
    source_owner,
    source_name,
    source_full_name,
    workspace_locator
`

type InsertRuntimeEnvironmentParams struct {
	RepositoryID             int64
	PullRequestID            int64
	Type                     string
	Status                   string
	TargetPrHeadCommitSha    string
	SourceGithubRepositoryID int64
	SourceOwner              string
	SourceName               string
	SourceFullName           string
}

func (q *Queries) InsertRuntimeEnvironment(ctx context.Context, arg InsertRuntimeEnvironmentParams) (RuntimeEnvironments, error) {
	row := q.db.QueryRow(ctx, insertRuntimeEnvironment,
		arg.RepositoryID,
		arg.PullRequestID,
		arg.Type,
		arg.Status,
		arg.TargetPrHeadCommitSha,
		arg.SourceGithubRepositoryID,
		arg.SourceOwner,
		arg.SourceName,
		arg.SourceFullName,
	)
	var i RuntimeEnvironments
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PullRequestID,
		&i.Type,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceGithubRepositoryID,
		&i.SourceOwner,
		&i.SourceName,
		&i.SourceFullName,
		&i.WorkspaceLocator,
	)
	return i, err
}

const listActiveRuntimeEnvironmentsByPullRequestAndType = `-- name: ListActiveRuntimeEnvironmentsByPullRequestAndType :many
SELECT
    id,
    repository_id,
    pull_request_id,
    type,
    status,
    target_pr_head_commit_sha,
    created_at,
    updated_at,
    source_github_repository_id,
    source_owner,
    source_name,
    source_full_name,
    workspace_locator
FROM runtime_environments
WHERE pull_request_id = $1
  AND type = $2
  AND status IN ('preparing', 'prepared')
ORDER BY id DESC
`

type ListActiveRuntimeEnvironmentsByPullRequestAndTypeParams struct {
	PullRequestID int64
	Type          string
}

func (q *Queries) ListActiveRuntimeEnvironmentsByPullRequestAndType(ctx context.Context, arg ListActiveRuntimeEnvironmentsByPullRequestAndTypeParams) ([]RuntimeEnvironments, error) {
	rows, err := q.db.Query(ctx, listActiveRuntimeEnvironmentsByPullRequestAndType, arg.PullRequestID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuntimeEnvironments
	for rows.Next() {
		var i RuntimeEnvironments
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.PullRequestID,
			&i.Type,
			&i.Status,
			&i.TargetPrHeadCommitSha,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceGithubRepositoryID,
			&i.SourceOwner,
			&i.SourceName,
			&i.SourceFullName,
			&i.WorkspaceLocator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuntimeEnvironmentStatus = `-- name: UpdateRuntimeEnvironmentStatus :one
UPDATE runtime_environments
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    repository_id,
    pull_request_id,
    type,
    status,
    target_pr_head_commit_sha,
    created_at,
    updated_at,
    source_github_repository_id,
    source_owner,
    source_name,
    source_full_name,
    workspace_locator
`

type UpdateRuntimeEnvironmentStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateRuntimeEnvironmentStatus(ctx context.Context, arg UpdateRuntimeEnvironmentStatusParams) (RuntimeEnvironments, error) {
	row := q.db.QueryRow(ctx, updateRuntimeEnvironmentStatus, arg.ID, arg.Status)
	var i RuntimeEnvironments
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PullRequestID,
		&i.Type,
		&i.Status,
		&i.TargetPrHeadCommitSha,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceGithubRepositoryID,
		&i.SourceOwner,
		&i.SourceName,
		&i.SourceFullName,
		&i.WorkspaceLocator,
	)
	return i, err
}
