// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlc

import (
	"context"
)

const getTriggerDispatchByID = `-- name: GetTriggerDispatchByID :one
SELECT
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    dispatch_type,
    status,
    dispatch_payload_json,
    last_error,
    processed_at,
    created_at
FROM trigger_dispatches
WHERE id = $1
`

func (q *Queries) GetTriggerDispatchByID(ctx context.Context, id int64) (TriggerDispatches, error) {
	row := q.db.QueryRow(ctx, getTriggerDispatchByID, id)
	var i TriggerDispatches
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.DispatchType,
		&i.Status,
		&i.DispatchPayloadJson,
		&i.LastError,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEventByID = `-- name: GetWebhookEventByID :one
SELECT
    id,
    delivery_id,
    github_event,
    event_type,
    repository_id,
    github_repository_id,
    status,
    ignored_reason,
    failure_message,
    payload_json,
    created_at
FROM webhook_events
WHERE id = $1
`

func (q *Queries) GetWebhookEventByID(ctx context.Context, id int64) (WebhookEvents, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByID, id)
	var i WebhookEvents
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.GithubEvent,
		&i.EventType,
		&i.RepositoryID,
		&i.GithubRepositoryID,
		&i.Status,
		&i.IgnoredReason,
		&i.FailureMessage,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertTriggerDispatch = `-- name: InsertTriggerDispatch :one
INSERT INTO trigger_dispatches (
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    dispatch_type,
    status,
    dispatch_payload_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    dispatch_type,
    status,
    dispatch_payload_json,
    last_error,
    processed_at,
    created_at
`

type InsertTriggerDispatchParams struct {
	WebhookEventID                  int64
	WebhookEventTriggerEvaluationID int64
	RepositoryID                    int64
	RepositoryTriggerID             int64
	DispatchType                    string
	Status                          string
	DispatchPayloadJson             []byte
}

func (q *Queries) InsertTriggerDispatch(ctx context.Context, arg InsertTriggerDispatchParams) (TriggerDispatches, error) {
	row := q.db.QueryRow(ctx, insertTriggerDispatch,
		arg.WebhookEventID,
		arg.WebhookEventTriggerEvaluationID,
		arg.RepositoryID,
		arg.RepositoryTriggerID,
		arg.DispatchType,
		arg.Status,
		arg.DispatchPayloadJson,
	)
	var i TriggerDispatches
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.DispatchType,
		&i.Status,
		&i.DispatchPayloadJson,
		&i.LastError,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO webhook_events (
    delivery_id,
    github_event,
    event_type,
    github_repository_id,
    status,
    payload_json
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (delivery_id) DO NOTHING
RETURNING
    id,
    delivery_id,
    github_event,
    event_type,
    repository_id,
    github_repository_id,
    status,
    ignored_reason,
    failure_message,
    payload_json,
    created_at
`

type InsertWebhookEventParams struct {
	DeliveryID         string
	GithubEvent        string
	EventType          string
	GithubRepositoryID *int64
	Status             string
	PayloadJson        []byte
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (WebhookEvents, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.DeliveryID,
		arg.GithubEvent,
		arg.EventType,
		arg.GithubRepositoryID,
		arg.Status,
		arg.PayloadJson,
	)
	var i WebhookEvents
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.GithubEvent,
		&i.EventType,
		&i.RepositoryID,
		&i.GithubRepositoryID,
		&i.Status,
		&i.IgnoredReason,
		&i.FailureMessage,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebhookEventTriggerEvaluation = `-- name: InsertWebhookEventTriggerEvaluation :one
INSERT INTO webhook_event_trigger_evaluations (
    webhook_event_id,
    repository_trigger_id,
    matched,
    reason,
    trigger_snapshot_json
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    webhook_event_id,
    repository_trigger_id,
    matched,
    reason,
    trigger_snapshot_json,
    created_at
`

type InsertWebhookEventTriggerEvaluationParams struct {
	WebhookEventID      int64
	RepositoryTriggerID int64
	Matched             bool
	Reason              string
	TriggerSnapshotJson []byte
}

func (q *Queries) InsertWebhookEventTriggerEvaluation(ctx context.Context, arg InsertWebhookEventTriggerEvaluationParams) (WebhookEventTriggerEvaluations, error) {
	row := q.db.QueryRow(ctx, insertWebhookEventTriggerEvaluation,
		arg.WebhookEventID,
		arg.RepositoryTriggerID,
		arg.Matched,
		arg.Reason,
		arg.TriggerSnapshotJson,
	)
	var i WebhookEventTriggerEvaluations
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.RepositoryTriggerID,
		&i.Matched,
		&i.Reason,
		&i.TriggerSnapshotJson,
		&i.CreatedAt,
	)
	return i, err
}

const listTriggerDispatchesByWebhookEventID = `-- name: ListTriggerDispatchesByWebhookEventID :many
SELECT
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    dispatch_type,
    status,
    dispatch_payload_json,
    last_error,
    processed_at,
    created_at
FROM trigger_dispatches
WHERE webhook_event_id = $1
ORDER BY id ASC
`

func (q *Queries) ListTriggerDispatchesByWebhookEventID(ctx context.Context, webhookEventID int64) ([]TriggerDispatches, error) {
	rows, err := q.db.Query(ctx, listTriggerDispatchesByWebhookEventID, webhookEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TriggerDispatches
	for rows.Next() {
		var i TriggerDispatches
		if err := rows.Scan(
			&i.ID,
			&i.WebhookEventID,
			&i.WebhookEventTriggerEvaluationID,
			&i.RepositoryID,
			&i.RepositoryTriggerID,
			&i.DispatchType,
			&i.Status,
			&i.DispatchPayloadJson,
			&i.LastError,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEventTriggerEvaluationsByWebhookEventID = `-- name: ListWebhookEventTriggerEvaluationsByWebhookEventID :many
SELECT
    id,
    webhook_event_id,
    repository_trigger_id,
    matched,
    reason,
    trigger_snapshot_json,
    created_at
FROM webhook_event_trigger_evaluations
WHERE webhook_event_id = $1
ORDER BY id ASC
`

func (q *Queries) ListWebhookEventTriggerEvaluationsByWebhookEventID(ctx context.Context, webhookEventID int64) ([]WebhookEventTriggerEvaluations, error) {
	rows, err := q.db.Query(ctx, listWebhookEventTriggerEvaluationsByWebhookEventID, webhookEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEventTriggerEvaluations
	for rows.Next() {
		var i WebhookEventTriggerEvaluations
		if err := rows.Scan(
			&i.ID,
			&i.WebhookEventID,
			&i.RepositoryTriggerID,
			&i.Matched,
			&i.Reason,
			&i.TriggerSnapshotJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTriggerDispatchFailed = `-- name: MarkTriggerDispatchFailed :one
UPDATE trigger_dispatches
SET
    status = 'failed',
    last_error = $2
WHERE id = $1
RETURNING
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    dispatch_type,
    status,
    dispatch_payload_json,
    last_error,
    processed_at,
    created_at
`

type MarkTriggerDispatchFailedParams struct {
	ID        int64
	LastError *string
}

func (q *Queries) MarkTriggerDispatchFailed(ctx context.Context, arg MarkTriggerDispatchFailedParams) (TriggerDispatches, error) {
	row := q.db.QueryRow(ctx, markTriggerDispatchFailed, arg.ID, arg.LastError)
	var i TriggerDispatches
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.DispatchType,
		&i.Status,
		&i.DispatchPayloadJson,
		&i.LastError,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTriggerDispatchProcessed = `-- name: MarkTriggerDispatchProcessed :one
UPDATE trigger_dispatches
SET
    status = 'processed',
    last_error = NULL,
    processed_at = NOW()
WHERE id = $1
RETURNING
    id,
    webhook_event_id,
    webhook_event_trigger_evaluation_id,
    repository_id,
    repository_trigger_id,
    dispatch_type,
    status,
    dispatch_payload_json,
    last_error,
    processed_at,
    created_at
`

func (q *Queries) MarkTriggerDispatchProcessed(ctx context.Context, id int64) (TriggerDispatches, error) {
	row := q.db.QueryRow(ctx, markTriggerDispatchProcessed, id)
	var i TriggerDispatches
	err := row.Scan(
		&i.ID,
		&i.WebhookEventID,
		&i.WebhookEventTriggerEvaluationID,
		&i.RepositoryID,
		&i.RepositoryTriggerID,
		&i.DispatchType,
		&i.Status,
		&i.DispatchPayloadJson,
		&i.LastError,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markWebhookEventFailed = `-- name: MarkWebhookEventFailed :one
UPDATE webhook_events
SET
    repository_id = $2,
    status = 'failed',
    ignored_reason = NULL,
    failure_message = $3
WHERE id = $1
RETURNING
    id,
    delivery_id,
    github_event,
    event_type,
    repository_id,
    github_repository_id,
    status,
    ignored_reason,
    failure_message,
    payload_json,
    created_at
`

type MarkWebhookEventFailedParams struct {
	ID             int64
	RepositoryID   *int64
	FailureMessage *string
}

func (q *Queries) MarkWebhookEventFailed(ctx context.Context, arg MarkWebhookEventFailedParams) (WebhookEvents, error) {
	row := q.db.QueryRow(ctx, markWebhookEventFailed, arg.ID, arg.RepositoryID, arg.FailureMessage)
	var i WebhookEvents
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.GithubEvent,
		&i.EventType,
		&i.RepositoryID,
		&i.GithubRepositoryID,
		&i.Status,
		&i.IgnoredReason,
		&i.FailureMessage,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const markWebhookEventIgnored = `-- name: MarkWebhookEventIgnored :one
UPDATE webhook_events
SET
    repository_id = $2,
    status = 'ignored',
    ignored_reason = $3,
    failure_message = NULL
WHERE id = $1
RETURNING
    id,
    delivery_id,
    github_event,
    event_type,
    repository_id,
    github_repository_id,
    status,
    ignored_reason,
    failure_message,
    payload_json,
    created_at
`

type MarkWebhookEventIgnoredParams struct {
	ID            int64
	RepositoryID  *int64
	IgnoredReason *string
}

func (q *Queries) MarkWebhookEventIgnored(ctx context.Context, arg MarkWebhookEventIgnoredParams) (WebhookEvents, error) {
	row := q.db.QueryRow(ctx, markWebhookEventIgnored, arg.ID, arg.RepositoryID, arg.IgnoredReason)
	var i WebhookEvents
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.GithubEvent,
		&i.EventType,
		&i.RepositoryID,
		&i.GithubRepositoryID,
		&i.Status,
		&i.IgnoredReason,
		&i.FailureMessage,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const markWebhookEventProcessed = `-- name: MarkWebhookEventProcessed :one
UPDATE webhook_events
SET
    repository_id = $2,
    status = 'processed',
    ignored_reason = NULL,
    failure_message = NULL
WHERE id = $1
RETURNING
    id,
    delivery_id,
    github_event,
    event_type,
    repository_id,
    github_repository_id,
    status,
    ignored_reason,
    failure_message,
    payload_json,
    created_at
`

type MarkWebhookEventProcessedParams struct {
	ID           int64
	RepositoryID *int64
}

func (q *Queries) MarkWebhookEventProcessed(ctx context.Context, arg MarkWebhookEventProcessedParams) (WebhookEvents, error) {
	row := q.db.QueryRow(ctx, markWebhookEventProcessed, arg.ID, arg.RepositoryID)
	var i WebhookEvents
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.GithubEvent,
		&i.EventType,
		&i.RepositoryID,
		&i.GithubRepositoryID,
		&i.Status,
		&i.IgnoredReason,
		&i.FailureMessage,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}
